import Head from 'next/head';
import Link from 'next/link';
import { format, parseISO } from 'date-fns';

import { blogPosts } from './../lib/data';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h3 className="text-center text-blue-400 mb-4">Featured Posts</h3>
          <div className="space-y-4">
            {blogPosts.map((post) => (
              <ListOfBlogPosts key={post.slug} {...post} />
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}

export function ListOfBlogPosts({ title, slug, date, description }) {
  return (
    <div className="border border-blue-100 rounded-lg p-4 shadow hover:shadow-md cursor-pointer transition duration-200 ease-in-out">
      <h2 className="text-lg font-bold">
        <Link href={`/post/${slug}`}>
          <a>{title}</a>
        </Link>
      </h2>
      <div className="font-extralight text-sm text-gray-600">
        {format(parseISO(date), 'MMMM do, yyyy')}
      </div>
      <div>{description}</div>
    </div>
  );
}
